Workflow:
  '@WorkflowId': '{6ace89be-f5fc-f011-8407-002248d75c63}'
  '@Name': TEST | PowerPlatformFederatedIdentity | Obtain FIC Service Access Token
  JsonFileName: /modernflows/6ace89be-f5fc-f011-8407-002248d75c63/TESTPowerPlatformFederatedIdentityObtainFICService-6ACE89BE-F5FC-F011-8407-002248D75C63.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 0.0.0
  IsCustomizable: 1
  RendererObjectTypeCode: 0
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': TEST | PowerPlatformFederatedIdentity | Obtain FIC Service Access Token
