#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities
{
	
	
	/// <summary>
	/// State of the Azure Key Vault Reference
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum az_keyvaultreference_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Status of the Azure Key Vault Reference
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum az_keyvaultreference_statuscode
	{
		
		/// <summary>
		/// The record has been validated with Azure Resource Manager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Validated = 3,
		
		/// <summary>
		/// The record has been created, but has not yet been validated with Azure Resource Manager
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 1,
		
		/// <summary>
		/// The record has been deactivated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deactivated = 2,
		
		/// <summary>
		/// Referenced Azure Key Vault not found or inaccessible
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidKeyVault = 4,
		
		/// <summary>
		/// Referenced object within Azure Key Vault not found or inaccessible
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidReference = 5,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("az_keyvaultreference")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class az_keyvaultreference : Microsoft.Xrm.Sdk.Entity
	{
		
				/// <summary>
		/// Available fields, a the time of codegen, for the az_keyvaultreference entity
		/// </summary>
		public partial class Fields
		{
			public const string az_displayname = "az_displayname";
			public const string az_keyvaultreferenceId = "az_keyvaultreferenceid";
			public const string Id = "az_keyvaultreferenceid";
			public const string az_name = "az_name";
			public const string az_resourceid = "az_resourceid";
			public const string az_resourcevalidatedon = "az_resourcevalidatedon";
			public const string az_templatename = "az_templatename";
			public const string az_templatesourcecomponentid = "az_templatesourcecomponentid";
			public const string az_templatesourcecomponentkeytypevalue = "az_templatesourcecomponentkeytypevalue";
			public const string az_templatesourceid = "az_templatesourceid";
			public const string az_templatesourcetypevalue = "az_templatesourcetypevalue";
			public const string az_templatetype = "az_templatetype";
			public const string az_templatevaultname = "az_templatevaultname";
			public const string az_templatevaulturi = "az_templatevaulturi";
			public const string az_type = "az_type";
			public const string az_vaultobjectidcollectionname = "az_vaultobjectidcollectionname";
			public const string az_vaultobjectiduri = "az_vaultobjectiduri";
			public const string az_vaulturi = "az_vaulturi";
			public const string az_version = "az_version";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string Referencedaz_keyvaultreference_templatesource_hierarchical = "Referencedaz_keyvaultreference_templatesource_hierarchical";
			public const string Referencingaz_keyvaultreference_templatesource_hierarchical = "az_keyvaultreference_templatesource_hierarchical";
			public const string az_keyvaultreference_templatesource_keyvaultreference = "az_keyvaultreference_templatesource_keyvaultreference";
			public const string lk_az_keyvaultreference_createdby = "lk_az_keyvaultreference_createdby";
			public const string lk_az_keyvaultreference_createdonbehalfby = "lk_az_keyvaultreference_createdonbehalfby";
			public const string lk_az_keyvaultreference_modifiedby = "lk_az_keyvaultreference_modifiedby";
			public const string lk_az_keyvaultreference_modifiedonbehalfby = "lk_az_keyvaultreference_modifiedonbehalfby";
			public const string user_az_keyvaultreference = "user_az_keyvaultreference";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public az_keyvaultreference() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "az_keyvaultreference";
		
		public const string EntityLogicalCollectionName = "az_keyvaultreferences";
		
		public const string EntitySetName = "az_keyvaultreferences";
		
		/// <summary>
		/// Display name for the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_displayname")]
		public string az_displayname
		{
			get
			{
				return this.GetAttributeValue<string>("az_displayname");
			}
			set
			{
				this.SetAttributeValue("az_displayname", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_keyvaultreferenceid")]
		public System.Nullable<System.Guid> az_keyvaultreferenceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("az_keyvaultreferenceid");
			}
			set
			{
				this.SetAttributeValue("az_keyvaultreferenceid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_keyvaultreferenceid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.az_keyvaultreferenceId = value;
			}
		}
		
		/// <summary>
		/// Name of the referenced Key Vault secret, key, or certificate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_name")]
		public string az_name
		{
			get
			{
				return this.GetAttributeValue<string>("az_name");
			}
		}
		
		/// <summary>
		/// Azure Resource Manager (ARM) Resource ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_resourceid")]
		public string az_resourceid
		{
			get
			{
				return this.GetAttributeValue<string>("az_resourceid");
			}
			set
			{
				this.SetAttributeValue("az_resourceid", value);
			}
		}
		
		/// <summary>
		/// Date and time when the record was last validated with Azure Resource Manager
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_resourcevalidatedon")]
		public System.Nullable<System.DateTime> az_resourcevalidatedon
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("az_resourcevalidatedon");
			}
			set
			{
				this.SetAttributeValue("az_resourcevalidatedon", value);
			}
		}
		
		/// <summary>
		/// Name of the referenced Key Vault secret, key, or certificate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatename")]
		public string az_templatename
		{
			get
			{
				return this.GetAttributeValue<string>("az_templatename");
			}
			set
			{
				this.SetAttributeValue("az_templatename", value);
			}
		}
		
		/// <summary>
		/// A reference to the version-less record serving as the parent containing the base information of a versioned Azure Key Vault Reference.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatesourcecomponentid")]
		public Microsoft.Xrm.Sdk.EntityReference az_templatesourcecomponentid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("az_templatesourcecomponentid");
			}
			set
			{
				this.SetAttributeValue("az_templatesourcecomponentid", value);
			}
		}
		
		/// <summary>
		/// For internal use
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatesourcecomponentkeytypevalue")]
		public string az_templatesourcecomponentkeytypevalue
		{
			get
			{
				return this.GetAttributeValue<string>("az_templatesourcecomponentkeytypevalue");
			}
		}
		
		/// <summary>
		/// A reference to the version-less record representing the parent containing the base information of a versioned Azure Key Vault Reference.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatesourceid")]
		public Microsoft.Xrm.Sdk.EntityReference az_templatesourceid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("az_templatesourceid");
			}
			set
			{
				this.SetAttributeValue("az_templatesourceid", value);
			}
		}
		
		/// <summary>
		/// For internal use
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatesourcetypevalue")]
		public string az_templatesourcetypevalue
		{
			get
			{
				return this.GetAttributeValue<string>("az_templatesourcetypevalue");
			}
		}
		
		/// <summary>
		/// Datatype of object in Azure Key Vault the record refers to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatetype")]
		public virtual az_keyvaultdataobjecttype? az_templatetype
		{
			get
			{
				return ((az_keyvaultdataobjecttype?)(EntityOptionSetEnum.GetEnum(this, "az_templatetype")));
			}
			set
			{
				this.SetAttributeValue("az_templatetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Name of the Key Vault storing the referenced secret, key or certificate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatevaultname")]
		public string az_templatevaultname
		{
			get
			{
				return this.GetAttributeValue<string>("az_templatevaultname");
			}
			set
			{
				this.SetAttributeValue("az_templatevaultname", value);
			}
		}
		
		/// <summary>
		/// URI to the Key Vault storing the referenced secret, key or certificate. Use: https://<vault-name>.vault.azure.net/
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatevaulturi")]
		public string az_templatevaulturi
		{
			get
			{
				return this.GetAttributeValue<string>("az_templatevaulturi");
			}
		}
		
		/// <summary>
		/// Datatype of object in Azure Key Vault the record refers to.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_type")]
		public virtual az_keyvaultdataobjecttype? az_type
		{
			get
			{
				return ((az_keyvaultdataobjecttype?)(EntityOptionSetEnum.GetEnum(this, "az_type")));
			}
		}
		
		/// <summary>
		/// For internal use
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_vaultobjectidcollectionname")]
		public string az_vaultobjectidcollectionname
		{
			get
			{
				return this.GetAttributeValue<string>("az_vaultobjectidcollectionname");
			}
		}
		
		/// <summary>
		/// URI that identifies the referenced object in Azure Key Vault
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_vaultobjectiduri")]
		public string az_vaultobjectiduri
		{
			get
			{
				return this.GetAttributeValue<string>("az_vaultobjectiduri");
			}
		}
		
		/// <summary>
		/// URI to the Key Vault storing the referenced secret, key or certificate. Use: https://<vault-name>.vault.azure.net/
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_vaulturi")]
		public string az_vaulturi
		{
			get
			{
				return this.GetAttributeValue<string>("az_vaulturi");
			}
		}
		
		/// <summary>
		/// Version of the referenced Key Vault secret, key, or certificate.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_version")]
		public string az_version
		{
			get
			{
				return this.GetAttributeValue<string>("az_version");
			}
			set
			{
				this.SetAttributeValue("az_version", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// State of the Azure Key Vault Reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual az_keyvaultreference_statecode? statecode
		{
			get
			{
				return ((az_keyvaultreference_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Status of the Azure Key Vault Reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual az_keyvaultreference_statuscode? statuscode
		{
			get
			{
				return ((az_keyvaultreference_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N az_keyvaultreference_templatesource_hierarchical
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("az_keyvaultreference_templatesource_hierarchical", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.az_keyvaultreference> Referencedaz_keyvaultreference_templatesource_hierarchical
		{
			get
			{
				return this.GetRelatedEntities<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.az_keyvaultreference>("az_keyvaultreference_templatesource_hierarchical", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.az_keyvaultreference>("az_keyvaultreference_templatesource_hierarchical", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// N:1 az_keyvaultreference_templatesource_hierarchical
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatesourceid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("az_keyvaultreference_templatesource_hierarchical", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.az_keyvaultreference Referencingaz_keyvaultreference_templatesource_hierarchical
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.az_keyvaultreference>("az_keyvaultreference_templatesource_hierarchical", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.SetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.az_keyvaultreference>("az_keyvaultreference_templatesource_hierarchical", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
		
		/// <summary>
		/// N:1 az_keyvaultreference_templatesource_keyvaultreference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("az_templatesourcecomponentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("az_keyvaultreference_templatesource_keyvaultreference")]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.KeyVaultReference az_keyvaultreference_templatesource_keyvaultreference
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.KeyVaultReference>("az_keyvaultreference_templatesource_keyvaultreference", null);
			}
			set
			{
				this.SetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.KeyVaultReference>("az_keyvaultreference_templatesource_keyvaultreference", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_az_keyvaultreference_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_az_keyvaultreference_createdby")]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser lk_az_keyvaultreference_createdby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser>("lk_az_keyvaultreference_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_az_keyvaultreference_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_az_keyvaultreference_createdonbehalfby")]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser lk_az_keyvaultreference_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser>("lk_az_keyvaultreference_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_az_keyvaultreference_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_az_keyvaultreference_modifiedby")]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser lk_az_keyvaultreference_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser>("lk_az_keyvaultreference_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_az_keyvaultreference_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_az_keyvaultreference_modifiedonbehalfby")]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser lk_az_keyvaultreference_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser>("lk_az_keyvaultreference_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_az_keyvaultreference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_az_keyvaultreference")]
		public FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser user_az_keyvaultreference
		{
			get
			{
				return this.GetRelatedEntity<FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities.SystemUser>("user_az_keyvaultreference", null);
			}
		}
	}
}
#pragma warning restore CS1591
