Workflow:
  '@WorkflowId': '{a8fb5f1f-f91e-f111-88b4-002248d75c63}'
  '@Name': TEST | PowerPlatformFederatedIdentity | On-Behalf-Of Token Bundle
  JsonFileName: /modernflows/a8fb5f1f-f91e-f111-88b4-002248d75c63/TESTPowerPlatformFederatedIdentityOn-Behalf-OfToke-A8FB5F1F-F91E-F111-88B4-002248D75C63.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': TEST | PowerPlatformFederatedIdentity | On-Behalf-Of Token Bundle
