#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FredrikHr.PowerPlatformFederatedIdentityCredentials.Plugins.Entities
{
	
	
	/// <summary>
	/// Data type of an object stored in Azure Key Vault
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum az_keyvaultdataobjecttype
	{
		
		/// <summary>
		/// A secret (e.g. a password or OAuth2 client secret) stored in Azure Key Vault
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Secret = 0,
		
		/// <summary>
		/// A certificate stored in Azure Key Vault
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Certificate = 1,
		
		/// <summary>
		/// A certificate with its entire chain stored in Azure Key Vault
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CertificatewithX509chain = 2,
	}
}
#pragma warning restore CS1591
