Workflow:
  '@WorkflowId': '{69111b18-2b6a-4e2f-8419-0b5b8ee9b285}'
  '@Name': TEST | PowerPlatformFederatedIdentity | Update Managed Identity
  JsonFileName: /modernflows/69111b18-2b6a-4e2f-8419-0b5b8ee9b285/TESTPowerPlatformFederatedIdentityUpdateManagedIde-69111B18-2B6A-4E2F-8419-0B5B8EE9B285.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 0.0.0
  IsCustomizable: 1
  RendererObjectTypeCode: 0
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  ModernFlowType: 0
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': TEST | PowerPlatformFederatedIdentity | Update Managed Identity
