###
# @name FederatedCredentialsManagedIdentityConfiguration
GET {{dataverse_instanceUrl}}/api/data/v9.2
  /managedidentities(1304a7e4-ed28-f011-8c4d-7c1e5226ec1f)
Authorization: oauth2 device_code dataverse
OData-Version: 4.01
OData-MaxVersion: 4.01
Prefer: odata.include-annotations=*

?? status == 200
?? body managedidentityid == 1304a7e4-ed28-f011-8c4d-7c1e5226ec1f

###
# @name CustomizeFederatedCredentialsManagedIdentity
# @ref FederatedCredentialsManagedIdentityConfiguration
# @import ./dataverse-webapi.http
# @ref DataverseInstanceInformation
@federatedid_clientId = {{$input Federated Identity Client Id}}
{{
  request.options.json = {
    applicationid: federatedid_clientId,
    tenantid: DataverseInstanceInformation.Detail.TenantId,
  }
}}
PATCH {{dataverse_instanceUrl}}/api/data/v9.2
  /managedidentities(1304a7e4-ed28-f011-8c4d-7c1e5226ec1f)
Authorization: oauth2 device_code dataverse
OData-Version: 4.01
OData-MaxVersion: 4.01
Prefer: odata.include-annotations=*, return=representation

?? status == 200
?? body managedidentityid == 1304a7e4-ed28-f011-8c4d-7c1e5226ec1f
