###
@keyvault_apiVersion = 7.4
@azureresourcemanager_apiVersion = 2022-04-01

###
# @name KeyVaultUriParameters
@keyvault_uriName = {{$input Azure KeyVault name}}
@keyvault_scope = https://{{keyvault_uriName}}.vault.azure.net/user_impersonation offline_access
{{
  exports[httpRegion.metaData["name"]] = {
    uriName: keyvault_uriName,
    scope: keyvault_scope,
  };
}}

###
# @name KeyVaultSecretBundleResource
# @ref KeyVaultUriParameters
GET https://{{KeyVaultUriParameters.uriName}}.vault.azure.net
  /secrets
  /{{$input Azure KeyVault secret name}}
  ?api-version={{keyvault_apiVersion}}
Authorization: oauth2 {{keyvault_grantType}} keyvault

?? status == 200
?? body id exists

###
# @name KeyVaultSecretResourceRbacRoleAssignments
# @ref KeyVaultSecretBundleResource
GET {{KeyVaultSecretBundleResource.id}}
  /providers/Microsoft.Authorization
  /roleAssignments
  ?api-version={{azureresourcemanager_apiVersion}}
  &$filter=atScope()
Authorization: oauth2 {{keyvault_grantType}} keyvault

?? status == 200
?? body value isArray
