###
@keyvault_apiVersion = 7.4

###
# @name KeyVaultUriParameters
@keyvault_uriName = {{$input Azure KeyVault name}}
@keyvault_scope = https://{{keyvault_uriName}}.vault.azure.net/user_impersonation offline_access
{{
  exports[httpRegion.metaData["name"]] = {
    uriName: keyvault_uriName,
    scope: keyvault_scope,
  };
}}

###
# @name ArmSubscriptionKeyVaultList
GET https://management.azure.com
  /subscriptions/{{arm_subscriptionid}}
  /providers/Microsoft.KeyVault
  /vaults
  ?api-version=2024-11-01
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body value isArray

###
# @name ArmKeyVaultResource
# @ref KeyVaultUriParameters
# @ref ArmSubscriptionKeyVaultList
GET https://management.azure.com{{ArmSubscriptionKeyVaultList.value.find(kv => kv.name === KeyVaultUriParameters.uriName).id}}
  ?api-version=2024-11-01
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body id exists

###
# @name ArmKeyVaultSecretResource
# @ref ArmKeyVaultResource
GET https://management.azure.com{{ArmKeyVaultResource.id}}
  /secrets/{{$input Azure KeyVault secret name}}
  ?api-version=2024-11-01
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body id exists

###
# @name ArmKeyVaultSecretResourceVersionsList
# @ref ArmKeyVaultSecretResource
GET https://management.azure.com{{ArmKeyVaultSecretResource.id}}
  /
  ?api-version=2024-11-01
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body id exists

###
# @name KeyVaultSecretBundleResource
# @ref ArmKeyVaultSecretResource
GET {{ArmKeyVaultSecretResource.properties.secretUri}}
  ?api-version={{keyvault_apiVersion}}
Authorization: oauth2 {{keyvault_grantType}} keyvault

?? status == 200
?? body id exists

###
# @name KeyVaultSecretResourceRbacRoleBuiltInRoleDefinitions
# @ref ArmKeyVaultSecretResource
GET https://management.azure.com{{ArmKeyVaultSecretResource.id}}
  /providers/Microsoft.Authorization
  /roleDefinitions
  ?api-version=2022-04-01
  &$filter=type eq 'BuiltInRole'
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body value isArray

###
# @name KeyVaultSecretResourceRbacRoleCustomRoleDefinitions
# @ref ArmKeyVaultSecretResource
GET https://management.azure.com{{ArmKeyVaultSecretResource.id}}
  /providers/Microsoft.Authorization
  /roleDefinitions
  ?api-version=2022-04-01
  &$filter=type eq 'CustomRole'
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body value isArray

###
# @name KeyVaultSecretResourceRbacRoleAssignments
# @ref ArmKeyVaultSecretResource
GET https://management.azure.com{{ArmKeyVaultSecretResource.id}}
  /providers/Microsoft.Authorization
  /roleAssignments
  ?api-version=2022-04-01
  &$filter=atScope()
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body value isArray

###
# @name KeyVaultSecretResourceRbacDenyAssignments
# @ref ArmKeyVaultSecretResource
GET https://management.azure.com{{ArmKeyVaultSecretResource.id}}
  /providers/Microsoft.Authorization
  /denyAssignments
  ?api-version=2022-04-01
  &$filter=atScope()
Authorization: oauth2 {{arm_grantType}} arm

?? status == 200
?? body value isArray

