environmentvariabledefinition:
  '@schemaname': test_pwrplatf_pp-fic_keyvaulturi
  description:
    '@default': Key Vault URI containing credentials for Service Principal Access Token Acquisition
    label:
      '@description': Key Vault URI containing credentials for Service Principal Access Token Acquisition
      '@languagecode': 1033
  displayname:
    '@default': TEST | PowerPlatformFederatedIdentity | Key Vault URI
    label:
      '@description': TEST | PowerPlatformFederatedIdentity | Key Vault URI
      '@languagecode': 1033
  introducedversion: 0.0.0
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
